site_name: Vcash docs
theme: readthedocs

pages:
 - Home : index.md
 - Block:
    - Generation:
        - 'Proof-of-Stake': block/generation/proof-of-stake.md
        - 'Proof-of-Work': block/generation/proof-of-work.md
    - block/pruning.md
 - Configuration:
   - Files:
     - 'config.dat': configuration/files/config.dat.md
 - Protocol:
   - Messages:
       - 'ztanswer': protocol/messages/ztanswer.md
       - 'ztlock': protocol/messages/ztlock.md
       - 'ztquestion': protocol/messages/ztquestion.md
       - 'ztvote': protocol/messages/ztvote.md
   - TCP:
       - protocol/TCP/encryption.md
       - protocol/TCP/routing.md
   - UDP:
       - protocol/UDP/encryption.md
       - protocol/UDP/routing.md
 - RPC:
   - Commands:
     - 'BackupWallet': RPC/commands/backupwallet.md
     - 'CheckWallet': RPC/commands/checkwallet.md
     - 'DatabaseFind': RPC/commands/databasefind.md
     - 'DatabaseStore': RPC/commands/databasestore.md
     - 'DumpPrivKey': RPC/commands/dumpprivkey.md
     - 'DumpWallet': RPC/commands/dumpwallet.md
     - 'EncryptWallet': RPC/commands/encryptwallet.md
     - 'GetAccount': RPC/commands/getaccount.md
     - 'GetAccountAddress': RPC/commands/getaccountaddress.md
     - 'GetBalance': RPC/commands/getbalance.md
     - 'GetBlock': RPC/commands/getblock.md
     - 'GetBlockCount': RPC/commands/getblockcount.md
     - 'GetBlockHash': RPC/commands/getblockhash.md
     - 'GetBlockTemplate': RPC/commands/getblocktemplate.md
     - 'GetDifficulty': RPC/commands/getdifficulty.md
     - 'GetIncentiveInfo': RPC/commands/getincentiveinfo.md
     - 'GetInfo': RPC/commands/getinfo.md
     - 'GetMiningInfo': RPC/commands/getmininginfo.md
     - 'GetNetworkHashPS': RPC/commands/getnetworkhashps.md
     - 'GetNewAddress': RPC/commands/getnewaddress.md
     - 'GetPeerInfo': RPC/commands/getpeerinfo.md
     - 'GetRawTransaction': RPC/commands/getrawtransaction.md
     - 'GetTransaction': RPC/commands/gettransaction.md
     - 'ImportPrivKey': RPC/commands/importprivkey.md
     - 'ListReceivedByAccount': RPC/commands/listreceivedbyaccount.md
     - 'ListReceivedByAddress': RPC/commands/listreceivedbyaddress.md
     - 'ListSinceBlock': RPC/commands/listsinceblock.md
     - 'ListTransactions': RPC/commands/listtransactions.md
     - 'RepairWallet': RPC/commands/repairwallet.md
     - 'SendMany': RPC/commands/sendmany.md
     - 'SendToAddress': RPC/commands/sendtoaddress.md
     - 'SetTxFee': RPC/commands/settxfee.md
     - 'SubmitBlock': RPC/commands/submitblock.md
     - 'ValidateAddress': RPC/commands/validateaddress.md
     - 'WalletDenominate': RPC/commands/walletdenominate.md
     - 'WalletLock': RPC/commands/walletlock.md
     - 'WalletPassphrase': RPC/commands/walletpassphrase.md
     - 'WalletPassphraseChange': RPC/commands/walletpassphrasechange.md
 - Technologies:
    - 'Node Incentives': technologies/node-incentives.md
    - 'ZeroTime': technologies/zerotime.md
